# __2.6 向量及其下标__

向量是什么？

1. 一个变量。
2. 可以容纳一个及多个数值或字符串。
3. 在R的向量里，只允许相同类型的值。

在R里，我们用_c_函数来创建一个向量。

例如：

首先，我们创建一个全是数字的向量

In [208]:
peas <- c(4, 7, 6, 5, 6, 7)
peas

[1] 4 7 6 5 6 7

如果我们想知道一个向量中包含的值的类型是什么，用class函数

In [209]:
class(peas)

[1] "numeric"

向量的元素的个数，或者向量的长度， length()

In [210]:
print(length(peas))

[1] 6


接着，我们创建一个全是字符的向量

In [211]:
str <- c('hello', 'world')
class(str)
str

[1] "character"

[1] "hello" "world"

当我们创建一个既有字符串又有数字的向量时，R会把数字自动升级为字符串。

In [212]:
mixed <- c('hello', 5)
mixed

[1] "hello" "5"

In [213]:
class(mixed)

[1] "character"

__创建向量的其他方法:__

1. :
2. seq(from, to, by)
3. rep(x, times)

In [214]:
vec <- 1:10
vec

[1]  1  2  3  4  5  6  7  8  9 10

In [215]:
vec <- seq(from=1, to=10, by=2)
vec

[1] 1 3 5 7 9

In [216]:
vec <- rep(x=10, times=10)
vec

[1] 10 10 10 10 10 10 10 10 10 10

有人会问，向量不是数学中几何空间的概念吗？为什么我在R里要学这个？我们看看向量到底是什么。

首先，在数学中，向量从零点指向空间中另一个点的一个箭头

  ![image.png](unnamed.png)
  
在上图中，三维空间中的红色向量可以用三个数字表示 （5， 8， 3）。

如果在N维空间中呢？ N个数字表示，对不对？

（$n_1$,$n_2$, ... ,$n_N$）

__问题：在数据处理中，向量是一行还是一列数据呢？__

In [217]:
t(peas)

[,1] [,2] [,3] [,4] [,5] [,6]
[1,] 4    7    6    5    6    7

In [218]:
#peas <- c(4, 7, 6, 5, 6, 7)
peas %*% t(peas)

[,1] [,2] [,3] [,4] [,5] [,6]
[1,] 16   28   24   20   24   28  
[2,] 28   49   42   35   42   49  
[3,] 24   42   36   30   36   42  
[4,] 20   35   30   25   30   35  
[5,] 24   42   36   30   36   42  
[6,] 28   49   42   35   42   49

![image.png](vec.png)

从上面的计算我们可以看出来，向量是一列数据。在一个数据集中，一个变量就是一列数据，对吧？ 它也就是一个向量。

![image](ice.png)

### 用空间几何的概念解释相关系数

![image](Vectors-Formula.jpg)

cor($\alpha$, $\beta$) = cosine($\theta$)

### __通过下标访问向量的元素__

__访问向量中的元素__

1. __访问单个元素：__ 向量的名字加上[]和下标（元素的顺序，从1开始）来获得或者访问相应的元素，例如peas[4]。
2. __访问多个元素：__

    1). 如果我们想访问多个元素的话，可以将我们想要访问的元素的下标放到另外一个向量里，再将这个向量放到[]里, 例如peas[c(2, 3, 6)]。  
    2). 可以去掉向量中的某些元素，用-加上下标向量，例如， peas[-c(1,4,5)]。

例子：

In [219]:
peas[4]

[1] 5

In [220]:
peas

[1] 4 7 6 5 6 7

In [221]:
pods <- c(2, 3, 6)
peas[pods]
peas[c(2,3,6)]
peas[-c(1,4,5)]

[1] 7 6 7

[1] 7 6 7

[1] 7 6 7

第二种访问向量元素的方法，可以使我们处理数据非常方便，例如，在一个向量中有缺失值（NA），vec <- c(1,2,3,4,NA, 5,6)。我们想把NA去掉，就可以用第二种访问向量元素的方法。在处理矩阵或Data Frame中行或列的缺失值时，我们可以用相同的办法

In [222]:
vec <- c(1,2,NA,3,4,NA, 5,6)
vec

[1]  1  2 NA  3  4 NA  5  6

In [223]:
vec1 <- vec[-3]
vec2 <- vec[-c(3,6)]
print("vec1")
vec1
print("vec2")
vec2

[1] "vec1"


[1]  1  2  3  4 NA  5  6

[1] "vec2"


[1] 1 2 3 4 5 6

### __逻辑下标__

逻辑下标是指一个值为TRUE或者FALSE的下标。我们可以通过逻辑向量来访问向量中的元素。逻辑向量就是包含TRUE或者FALSE的向量，例如，（TRUE, TRUE, FALSE, TRUE, FALSE）。

当然，这个逻辑向量的长度必须和数据向量相同。如果逻辑向量的长度小于数据向量，会发生什么呢？

例如：

In [224]:
x <- 0:10
logic_vec1 <- c(TRUE,TRUE,TRUE,TRUE,TRUE,FALSE, FALSE,FALSE,FALSE,FALSE, FALSE)
logic_vec2 <- c(TRUE,TRUE,TRUE,TRUE,TRUE,FALSE, FALSE,FALSE,FALSE)

In [225]:
x[logic_vec1]

[1] 0 1 2 3 4

In [226]:
x[logic_vec2]

[1]  0  1  2  3  4  9 10

通过逻辑下标读访问数据向量的元素的好处：

比如，我们想找到向量中小于某个数值的所有元素，或者所有元素的个数。

In [227]:
x < 5

[1]  TRUE  TRUE  TRUE  TRUE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE

In [228]:
x[x<5]

[1] 0 1 2 3 4

In [229]:
sum(x[x<5])

[1] 10

在R中，逻辑向量可以自动转化成数字，TRUE=1, FALSE=0

In [230]:
sum(x<5)

[1] 5

In [231]:
1*(x<5)

[1] 1 1 1 1 1 0 0 0 0 0 0

In [232]:
x*(x<5)

[1] 0 1 2 3 4 0 0 0 0 0 0

如果我们知道一个数值，如何获得它的下标呢？

In [234]:
which(x == 5)

[1] 6

In [233]:
x == 5

[1] FALSE FALSE FALSE FALSE FALSE  TRUE FALSE FALSE FALSE FALSE FALSE

In [ ]:
which(x==min(x))
which(x==max(x))

## 2.7 向量函数

|函数| 功能|
|:-------|:------|
|max(x)| 求向量x的最大值|
|min(x)| 求向量x的最大值|
|sum(x)| 求向量x中的所有数值的和|
|mean(x)| 求向量x的平均值|
|median(x)| 求向量x的中位数|
|range(x) |返回包括向量x的最小值和最大值的向量|
|var(x) |求向量x的样本方差|
|cor(x,y) |求向量x和y的相关系数|
|sort(x) |对向量x中的元素进行排序，并返回一个排序后的新向量|
|rank(x) |返回一个所有向量x的元素的排位的向量|
|order(x)|返回一个包含向量x中所有元素升序排列的整数向量|
|quantile(x) |返回一个包含向量x的最小值, 25百分位数, 中位数,75百分位数, 和最大值的向量|
|cumsum(x)| 返回一个将向量x中元素按索引顺序累加的向量，例如向量x=(1,2,3),返回向量就是（1，3，6）|
|cumprod(x) |返回一个将向量x中元素按索引顺序累乘的向量，例如向量x=(1,2,3),返回向量就是（1，2，6）|
|cummax(x) |vector of non-decreasing numbers which are the cumulative maxima of the values in x up to that point|
|cummin(x)| vector of non-increasing numbers which are the cumulative minima of the values in x up to that point|
|pmax(x,y,z)| vector, of length equal to the longest of x, y or z, containing the maximum of x, y or z for the ith position in each|
|pmin(x,y,z)| vector, of length equal to the longest of x, y or z, containing the minimum of x, y or z for the ith position in each|
|colMeans(x)| 求dataframe x或矩阵x的每列的平均值|
|colSums(x)| 求dataframe x或矩阵x的每列的总和|
|rowMeans(x)|求dataframe x或矩阵x的每行的平均值|
|rowSums(x) |求dataframe x或矩阵x的每行的总和|

## 使用tapply计算平均值表

In [235]:
data(mtcars)
attach(mtcars)

The following objects are masked from mtcars (pos = 3):

    am, carb, cyl, disp, drat, gear, hp, mpg, qsec, vs, wt



In [236]:
head(mtcars)

mpg  cyl disp hp  drat wt    qsec  vs am gear carb
Mazda RX4         21.0 6   160  110 3.90 2.620 16.46 0  1  4    4   
Mazda RX4 Wag     21.0 6   160  110 3.90 2.875 17.02 0  1  4    4   
Datsun 710        22.8 4   108   93 3.85 2.320 18.61 1  1  4    1   
Hornet 4 Drive    21.4 6   258  110 3.08 3.215 19.44 1  0  3    1   
Hornet Sportabout 18.7 8   360  175 3.15 3.440 17.02 0  0  3    2   
Valiant           18.1 6   225  105 2.76 3.460 20.22 1  0  3    1

In [237]:
tapply(hp, cyl, mean)

4         6         8 
 82.63636 122.28571 209.21429

In [238]:
#sample variance
tapply(hp, cyl, var)

4         6         8 
 438.2545  588.5714 2598.6429

In [239]:
tapply(hp, list(cyl, am), mean)

0         1       
4  84.66667  81.8750
6 115.25000 131.6667
8 194.16667 299.5000

用na.rm=TRUE去掉缺失值。

In [240]:
tapply(hp, cyl, mean, na.rm=TRUE)

4         6         8 
 82.63636 122.28571 209.21429

我们可以用trim来去掉一些极端值（outliers）。trim的取值范围是0到0.5，用于决定去掉多少比例的数据。

In [241]:
tapply(hp, cyl, mean, trim=0.2)

4         6         8 
 81.85714 115.20000 203.00000

## 用aggregate函数计算分组的统计值

通过aggregate函数，我们可以计算分组数据的统计值，如平均值，标准差，最大值，最小值，中位数等。

* 一对一：aggreate(y ~ x, mean)
* 一对多: aggreate(y ~ x+w, mean)
* 多对一: aggreate(cbind(y,z) ~ x, mean)
* 多对多: aggreate(cbind(y,z) ~ x+w, mean)

In [242]:
aggregate(hp ~ cyl, mtcars, mean)

cyl hp       
1 4    82.63636
2 6   122.28571
3 8   209.21429

In [243]:
aggregate(hp ~ cyl + am, mtcars, mean)

cyl am hp       
1 4   0   84.66667
2 6   0  115.25000
3 8   0  194.16667
4 4   1   81.87500
5 6   1  131.66667
6 8   1  299.50000

In [244]:
aggregate(cbind(hp,  mpg)~ cyl, mtcars, mean)

cyl hp        mpg     
1 4    82.63636 26.66364
2 6   122.28571 19.74286
3 8   209.21429 15.10000

In [245]:
aggregate(cbind(hp,  mpg)~ cyl + am, mtcars, mean)

cyl am hp        mpg     
1 4   0   84.66667 22.90000
2 6   0  115.25000 19.12500
3 8   0  194.16667 15.05000
4 4   1   81.87500 28.07500
5 6   1  131.66667 20.56667
6 8   1  299.50000 15.40000

## Rank, Sort和Order

* Rank: 数据的等级。rank返回一列数据中所有数据点的等级值，其中，最小值的rank是1， 最大值的rank是这列数据的长度length(data)。如果两个数据点的值相等，比如我们数据中有两个188的数据点，等级分别为8和9，我们取8和9的平均值8.5作为这两个数据点的rank。如果多个数据点的值相等，方法相同。
* Sort: 将一列数据的数据点以递增的顺序排序，如果想递减排序可以用rev(sort(x)。
* Order: 返回排序后每个数据点在向量中原来的位置。比较难理解，后边我们通过一个例子解释。

In [246]:
rank(c(1,2,2,2,3))

[1] 1 3 3 3 5

In [247]:
x <- c(5,6,3,8,1)
Sort <- sort(x)
Sort

[1] 1 3 5 6 8

In [248]:
rev_sort <- rev(sort(x))
rev_sort

[1] 8 6 5 3 1

In [249]:
Order <- order(x)
Order

[1] 5 3 1 2 4

In [250]:
Seq <- 1:5
data.frame(Seq,x, Sort, Order)

Seq x Sort Order
1 1   5 1    5    
2 2   6 3    3    
3 3   3 5    1    
4 4   8 6    2    
5 5   1 8    4

## Unique和Duplicated的区别

In [251]:
names <- c("Xiaoming","Ermao","Ermao","Xiaoming","Ermao","Zhuzi")

In [252]:
table(names)

names
   Ermao Xiaoming    Zhuzi 
       3        2        1 

In [253]:
unique(names)

[1] "Xiaoming" "Ermao"    "Zhuzi"

In [254]:
duplicated(names)

[1] FALSE FALSE  TRUE  TRUE  TRUE FALSE

In [255]:
names[!duplicated(names)]

[1] "Xiaoming" "Ermao"    "Zhuzi"

## Union、Intersection和Setdiff

In [256]:
setA <- c("a", "b", "c", "d", "e")
setB <- c("d", "e", "f", "g")

In [257]:
union(setA,setB)

[1] "a" "b" "c" "d" "e" "f" "g"

In [258]:
intersect(setA,setB)

[1] "d" "e"

In [259]:
setdiff(setA,setB)

[1] "a" "b" "c"

In [260]:
setdiff(setB,setA)

[1] "f" "g"

# 2.8 矩阵和数组（Matrices and arrays）

### 构造一个数组

数组和向量不同，可以是一维的，也可以是多维的。

In [261]:
y <- 1:24

dim(y) <- c(2,4,3)

y

![image](arr1.png)

dim(y) <- c(3, 2, 4)

y

![image](arr2.png)

## 矩阵

在R中，矩阵是一个二维的数组。

In [262]:
X <- matrix(c(1,0,0,0,1,0,0,0,1),nrow=3)
X

[,1] [,2] [,3]
[1,] 1    0    0   
[2,] 0    1    0   
[3,] 0    0    1

In [263]:
attributes(X)
dim(X)

$dim
[1] 3 3

[1] 3 3

In [264]:
vector <- c(1,2,3,4,4,3,2,1)
V <- matrix(vector,byrow=T,nrow=2)
V

[,1] [,2] [,3] [,4]
[1,] 1    2    3    4   
[2,] 4    3    2    1

In [266]:
V <- matrix(vector,byrow=FALSE,nrow=2)
V

[,1] [,2] [,3] [,4]
[1,] 1    3    4    2   
[2,] 2    4    3    1

In [267]:
t(V)

[,1] [,2]
[1,] 1    2   
[2,] 3    4   
[3,] 4    3   
[4,] 2    1

In [268]:
colnames(V) <- colnames(V,do.NULL=FALSE,prefix="var")

In [269]:
V

var1 var2 var3 var4
[1,] 1    3    4    2   
[2,] 2    4    3    1

In [270]:
rownames(V) <- rownames(V,do.NULL=FALSE,prefix="participant")
V

var1 var2 var3 var4
participant1 1    3    4    2   
participant2 2    4    3    1

In [271]:
dimnames(V) <- list(NULL,paste("drug.",1:4,sep=""))
V

drug.1 drug.2 drug.3 drug.4
[1,] 1      3      4      2     
[2,] 2      4      3      1

## 计算矩阵的行和列的统计值

In [272]:
#mean of column 4
mean(V[,4])

[1] 1.5

In [273]:
#mean of row 1
mean(V[1,])

[1] 2.5

In [274]:
rowSums(V)
rowMeans(V)
colSums(V)
colMeans(V)

[1] 10 10

[1] 2.5 2.5

drug.1 drug.2 drug.3 drug.4 
     3      7      7      3

drug.1 drug.2 drug.3 drug.4 
   1.5    3.5    3.5    1.5

## apply, sapply, 和 lapply

In [275]:
(X <- matrix(1:24,nrow=4))

[,1] [,2] [,3] [,4] [,5] [,6]
[1,] 1    5     9   13   17   21  
[2,] 2    6    10   14   18   22  
[3,] 3    7    11   15   19   23  
[4,] 4    8    12   16   20   24

In [276]:
apply(X, 1, sum)

[1] 66 72 78 84

In [277]:
apply(X, 2, sum)

[1] 10 26 42 58 74 90

In [278]:
#Apply the function on each of the elements in the vector.
sapply(3:7, seq)

[[1]]
[1] 1 2 3

[[2]]
[1] 1 2 3 4

[[3]]
[1] 1 2 3 4 5

[[4]]
[1] 1 2 3 4 5 6

[[5]]
[1] 1 2 3 4 5 6 7

In [279]:
seq(3)

[1] 1 2 3

# 2.9 随机数、抽样和打乱顺序

## 随机数

随机数对于统计学和密码学很重要。 

* 在密码学中，随机数可以生成密钥。当然大多数时候我们谈到随机数都是伪随机数，也就是通过数学模型生成的随机数。

* 在统计中，我们使用随机数生成器进行数据抽样，或者可以根据某一概率分布生成随机数来验证统计方法，例如以下例子中的runif，就是基于标准均匀分布（uniform distribution）生成随机数。

一般在生成实验用的随机数的时候，我们要先设定seed,种子数，就是数学模型用于生成随机数时的起始数。设定seed后，再次使用相同的seed，生成的随机数都会和第一次设定seed后生成的第一组数相同。

In [280]:
set.seed(375)

In [281]:
runif(4)

[1] 0.9613669 0.6918535 0.7302684 0.9228566

In [282]:
runif(4)

[1] 0.16038037 0.96427987 0.52880907 0.08660864

In [283]:
set.seed(375)

In [284]:
runif(4)

[1] 0.9613669 0.6918535 0.7302684 0.9228566

## 抽样函数

生成随机数在我们现在这个阶段还用不上。但是抽样函数sample对我们很重要。

抽样函数会将我们的数据打乱，并生成一个随机顺序的一个向量。

抽样函数对我们随机化实验设计非常有用，比如给我们实验对象的群体编上号，通过抽样函数随机抽取实验对象。

In [285]:
y <- c(8,3,5,7,6,6,8,9,2,3,9,4,10,4,11)

In [286]:
sample(y)

[1] 11  4  8  4  3  9  7  6  2  6  5  3  8  9 10

当然我们还可以指定抽样的个数，以及是否重复抽样。重复抽样常用于机器学习中的bootstrapping，通过多次重复随机抽样重新建立起新的数据样本。

In [287]:
sample(y, 5)

[1] 8 3 3 4 2

In [288]:
sample(y, replace=T)

[1]  9  3 11  4  5  9  3  9  7  6 10 10  6  3  5